services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/var
      - /app/vendor

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###
